# Generated by Django 2.0 on 2017-12-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste', models.CharField(max_length=250)),
                ('cocktail_name', models.CharField(max_length=250)),
                ('difficulty', models.CharField(max_length=250)),
                ('cocktail_pic', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Spirits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spirit_name', models.CharField(max_length=50)),
            ],
        ),
    ]
