# Generated by Django 2.0 on 2017-12-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spirits',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='id',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='strength',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='cocktail_name',
            field=models.CharField(max_length=250, primary_key='true', serialize=False),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='taste',
            field=models.CharField(max_length=65),
        ),
    ]
