# Generated by Django 2.0 on 2017-12-18 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_auto_20171218_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spirits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spirit_name', models.CharField(max_length=50)),
                ('spirit_color', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cocktail',
            name='abc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='strength',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='spirits',
            name='cocktail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktails.Cocktail'),
        ),
    ]
