# Generated by Django 2.0 on 2017-12-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_auto_20171218_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='abc',
        ),
    ]
