# Generated by Django 2.0 on 2017-12-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0004_remove_cocktail_abc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='strength',
            field=models.CharField(max_length=100),
        ),
    ]
