# Generated by Django 2.0 on 2017-12-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0005_auto_20171218_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='abc',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
