# Generated by Django 2.0 on 2017-12-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0007_cocktail_bgh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='abc',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='bgh',
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='taste',
            field=models.CharField(max_length=5),
        ),
    ]
