# Generated by Django 2.0 on 2017-12-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0008_auto_20171218_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='taste',
            field=models.CharField(max_length=4),
        ),
    ]
