# Generated by Django 2.0 on 2017-12-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0009_auto_20171218_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='cocktail_name',
            field=models.CharField(max_length=50, primary_key='true', serialize=False),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='difficulty',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='strength',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='taste',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='spirits',
            name='spirit_color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='spirits',
            name='spirit_name',
            field=models.CharField(max_length=20),
        ),
    ]
