# Generated by Django 2.0 on 2017-12-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0010_auto_20171218_1222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spirits',
            new_name='Spirit',
        ),
    ]
