# Generated by Django 2.0 on 2017-12-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0011_auto_20171218_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='spirit',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
