# Generated by Django 2.0 on 2017-12-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0013_cocktail_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='cocktail_pic',
            field=models.FileField(upload_to=''),
        ),
    ]
